### ISSUE TITLE
Refreshed Repo

### ISSUE THREAD

**Issue by TechnologyClassroom** [JanusLinux/utils#1]
I noticed the JanusLinux repos are continually destroyed and rebuilt.  This loses Issues, Stars, and other features from Github.

To prevent this, use git instead of the Github web portal to manage these repos.

**Comment by protonesso** [comment]
But recently I've restored them

**Comment by TechnologyClassroom** [comment]
Maybe I looked before you restored them.  JanusLinux/janus does look different from the last time I reviewed it.
